Generation step added to readme.
angular-fullstack/generator-angular-fullstack pull request #2736
Opened 2018-06-29 06:58 UTC by gintsgints

- [ x] I have read the [Contributing Documents](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/contributing.md)
- [ x] My commit(s) follow the [AngularJS commit message guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/)
- [ x] The generator's tests pass (`generator-angular-fullstack$ npm test`)

2018-06-29 06:59 UTC, Awk34 approved these changes

2018-06-29 07:00 UTC, Awk34 commented on readme.md
> +and run yoeman to generate your fullstack app:
yoeman -> Yeoman

2018-06-29 07:00 UTC, Awk34 requested changes
see above

2022-10-05 16:28 UTC, aniket12july approved these changes

2022-12-16 20:24 UTC, closed without merging